/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pdgcxaalgtlvtkgykywp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZ2N4YWFsZ3RsdnRrZ3lreXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxNDUwMTksImV4cCI6MjA5NTcyMTAxOX0.z2cpNLi7Vrc-V1-xgCK7s8Q8Md7fOU_lFnFghTmDykU"