#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const gitDir = path.join(rootDir, '.git');
const hooksDir = path.join(gitDir, 'hooks');
const preCommitHookPath = path.join(hooksDir, 'pre-commit');

function setup() {
  console.log('[+] Setting up Git hooks...');

  if (!fs.existsSync(gitDir)) {
    console.log('[!] Not a Git repository, skipping hook installation.');
    return;
  }

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Define hook content (standard shell script that runs on bash-like environments)
  const hookContent = `#!/bin/sh
# Autogenerated by setup-hooks.js - DO NOT EDIT

echo "[Git Hook] Checking for credentials/secrets..."
node scripts/scan-secrets.js --staged
if [ $? -ne 0 ]; then
  echo "[Git Hook] Commit aborted due to potential credential leak."
  exit 1
fi

echo "[Git Hook] Credentials check passed."
exit 0
`;

  try {
    fs.writeFileSync(preCommitHookPath, hookContent, { encoding: 'utf8', mode: 0o755 });
    
    // Explicitly set executable permission (important for non-Windows platforms)
    try {
      fs.chmodSync(preCommitHookPath, '755');
    } catch (e) {
      // Ignore chmod errors if they happen on platforms where it's not supported
    }

    console.log('[+] Pre-commit hook successfully installed at: .git/hooks/pre-commit');
  } catch (error) {
    console.error('[-] Failed to write git pre-commit hook:', error.message);
  }
}

setup();
